name: Deploy to AWS

on:
  push:
    branches:
      - main  # 만약 브랜치가 master라면 master로 수정하세요!

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # 프로젝트 폴더로 이동 (폴더명 smash가 맞는지 꼭 확인!)
            cd smash
            
            # 최신 코드 당겨오기
            git fetch --all
            git reset --hard origin/main
            
            pm2 restart all